### ISSUE TITLE
[macOS intel x64]Sample project TinyLink crashed with an Assert : `Application is already running`

### ISSUE THREAD

**Issue by zhengying** [FosterFramework/Foster#16]
OS: macOS 13.4 intel x64
I tried two samples (Froggymark, TinyLink), all crashed at the same assertion  `Application is already running`
------ error:
Process terminated. Assertion failed.
Application is already running
   at Foster.Framework.App.Run(String applicationName, Int32 width, Int32 height, Boolean fullscreen) in /Users/test1/Downloads/Foster-main/Framework/App.cs:line 224
   at TinyLink.Program.Main() in /Users/test1/Downloads/Foster-main/Samples/TinyLink/Source/Manager.cs:line 12
zsh: abort

**Comment by NoelFB** [comment]
Hey! I think the likely issue is that I haven't built the [macOS native library](https://github.com/NoelFB/Foster/tree/main/Platform) and included it in the repo yet. I'll work on getting that in today. It's slightly weird that it's asserting on that though, instead of when trying to load the library.

**Comment by NoelFB** [comment]
This should now be addressed with the latest commits including a macOS dylib for the native library. Can re-open this issue if the problem is still occurring after that!
