### ISSUE TITLE
Drawing transparent textures

### ISSUE THREAD

**Issue by codecat** [FosterFramework/Foster#76]
I seem to be unable to draw transparent textures properly. The transparency byte is 11 according to Aseprite, but it shows as almost opaque:

![image](https://github.com/FosterFramework/Foster/assets/136534/30909776-0371-447f-94a4-fce2e00360d5)

From my XNA days I remember there was some kind of "premultiplied alpha" setting that can be used for rendering to fix something similar - does Foster have anything like that that I'm missing?

**Comment by kuujoo** [comment]
Batcher uses 'premultiplied alpha' blending mode, but I'm not sure if Aseprite premultiplies images by default.

Try to premultiply images:

```
 Aseprite sp = new Aseprite("Content/Sprites/test.ase");
 var image = sp.RenderFrame(0);
 image.Premultiply();
 _tex = new Texture(image);
```

**Comment by codecat** [comment]
Calling `Premultiply()` seemed to work! I am actually just using png's though, not `.ase` files for rendering these.
```cs
Image = new Image(path);
Image.Premultiply();
```
Is that the intended workflow, to call `Premultiply()` if needed?

**Comment by kuujoo** [comment]
I think Foster should automatically call it, since Batcher uses premultiplied blending by default.

@NoelFB

**Comment by NoelFB** [comment]
Often the premultiply process is applied in a pre-build step to make loading at runtime faster. If images automatically performed this step on-load it would break any images that have already had this process applied (and also be much slower if you don't care about premultiplying the image).

So yes, it's currently all intentional. I'm not against making this process more clear, though, and perhaps adding more ways to simplify the process. It might also be nice to make a normal non-premultiplied blend option that can be used if you don't want to use the premultiply blending.

**Comment by codecat** [comment]
I see, that makes sense! Is there any information on the process of premultiplying images outside of at runtime?

**Comment by NoelFB** [comment]
Generally

> Is there any information on the process of premultiplying images outside of at runtime?

Generally you can just apply the premultiply and then save it as a .png/.qoi again. Or alternatively save it in some custom format for faster loading.

With the addition of NonPremultiplied blendmode I think I'll close this but later on when there's more docs making this clearer would be good.
